simplesocial/MachineLearningApi/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'MachineLearningApi'

urlpatterns = [
path('display/', views.userDetails),
path('ImportData/', views.DataImportFile.as_view(), name="importDatafile"),
path(r'^upload/csv/$', views.upload_csv, name='upload_csv'),
path('MachineLearningApi/preprocess/', views.PreprocessPage, name='preprocess'),
path('MachineLearningApi/preprocess/display/', views.userDetails,name='display'),
path('MachineLearningApi/preprocess/partitiondata/',views.partitiondata,name='partitiondata'),
path('MachineLearningApi/preprocess/partitiondata/CreateModel/',views.CreateModel,name='CreateModel'),
path('MachineLearningApi/preprocess/partitiondata/CreateModel/display/', views.userDetails,name='userDetails'),
path('MachineLearningApi/preprocess/partitiondata/CreateModel/display/userdetails/', views.userDetails,name='display'),
path('MachineLearningApi/preprocess/partitiondata/CreateModel/display/userdetails/datacleaning', views.Datacleaning,name='datacleaning'),
path('MachineLearningApi/preprocess/partitiondata/CreateModel/display/userdetails/datacleaning/datacleaninglatest', views.Datacleaning,name='datacleaned'),
path('MachineLearningApi/preprocess/partitiondata/CreateModel/display/userdetails/datacleaning/datacleaninglatest/replaceValues', views.replaceValues,name='replaceValues'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/posts/urls.py
from django.urls import path
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings

urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    # path('userdetails/', views.userDetails),
    # path('display/', views.userDetails),
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('posts/', include("posts.urls", namespace="posts")),
    path('groups/',include("groups.urls", namespace="groups")),
    path('MachineLearningApi/',include("MachineLearningApi.urls", namespace="MachineLearningApi")),
    path('MachineLearningApi/preprocess/', views.PreprocessPage.as_view(), name="preprocess"),
    
    path('MachineLearningApi/preprocess/partitiondata/',views.partitiondata.as_view(),name='partitiondata'),
    path('MachineLearningApi/preprocess/partitiondata/CreateModel/',views.CreateModel.as_view(),name='CreateModel'),
    
    
]


# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplesocial/templates/CreateModel.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<head>
</head>
<!-- <h1> Lets create our first model</h1> -->


<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <!-- <tr>
                {{loaded_data | safe}}
        </tr> -->

    </thead>
    <tbody>
            <tr> <h2 style="color:rgb(25, 28, 236);font-family:verdana;"> <b>Model </b>  </h2>
              <p>After partitioning the data into training and testing data, I will build a model. I have defined a train function which  takes in two arguements X and T. X is a one - dimensional matrix containg the training data while T is  a two-dimensional matrix containing the target values. The train method standardizes the input data X by calculating its mean and standard deviation. The mean and standard deviations are used to calculate the weights for the data and the function in the end returns a dictionary with the means, standard deviation and weights associated the data. The means, stds and weights are defined below.</p>
                     <table>
                            <tr>
                              {% for key in model.keys %}
                                  <th>{{key}}</th>
                              {% endfor %}
                            </tr>
                            <tr>
                              {% for value in model.values %}
                                  <td>
                                   {% for v in value %}
                                     {{v}}
                                   {% endfor %}
                                 </td>
                              {% endfor %}
                            </tr>
                          </table>
                          <h2 style="color:rgb(25, 28, 236);font-family:verdana;"> <b>Predicted Model </b>  </h2>
                          <p>When we have build a model, we try to make some predictions. I have defined a "Use" function that takes in two parameters model and X. The model parameter is returned by the train function while X is a two - dimensional matrix containg the training data. In this method we will be also standardizing the input X by using the already calculated means and Standard deviations as in the train function. The function returns a set of prediction values based on the input X</p>
                          {{predictedmodel | safe}}
                          <h2 style="color:rgb(25, 28, 236);font-family:verdana;"> <b>Error </b>  </h2>
                          <p>The error is calculated using the RMSE method. RMSE stands for root-mean-square error. It is used to measure  the difference between values  predicted by the  model(train function) and the target values. This function takes in the predict and T parameters. Predict correspnds to the values predicted while T corresponds to the target values.</p> 
                          Error {{error}} 
                          {{html | safe}}
                         
                            
                     
            </tr>
            <form action="{% url 'MachineLearningApi:userDetails' %}"  >
              <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> User Details</button>
              </form>
        <!-- {{test}}
        {% for ad in test %} -->
        
    <!-- {% endfor %} -->
    </tbody>
</table>
{% endblock %}

simplesocial/templates/PartitionedData.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<!-- <h1> Congratulations! Let's look at step number 2 in the machine learning process</h1> -->


<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <!-- <tr>
                {{loaded_data | safe}}
        </tr> -->

    </thead>
    <tbody>
            <tr>
                    <!-- lights data
                    {{filedf | safe}} -->
                    <h2 style="color:rgb(25, 28, 236);font-family:verdana;"> <b>Partition Data </b>  </h2>
                    
                    <p>After reading in the data from a csv file, we have to partition the data set into training and testing datasets. Generally, 80/20 rule is followed when partitioning the data. 80% of the data is considered as training data, while the rest is used for testing the model.  X is the input data, while T contains the target valuesSome of the functions used in the partitioning the data are  Train, Model, RMSE, TrainSGD.For more information about the functions, please visit my github profile. We partition the data in order to calculate the weights assigned to the data set which will help to make good predictions.</p>
                    &nbsp;
                    <h5 style="color:rgb(25, 116, 236);font-family:verdana;"> <b>Xtrain </b>  </h5>
                    
                     {{Xtrain1 | safe}}
                    <!-- figure {{ figure | safe}} -->
                    &nbsp;
                    <h5 style="color:rgb(25, 116, 236);font-family:verdana;"> <b>Ttrain </b>  </h5>
                    {{Ttrain1 | safe}}
                    <!-- figure {{ figure | safe}} -->
                    &nbsp;
                    <h5 style="color:rgb(25, 116, 236);font-family:verdana;"> <b>Xtest </b>  </h5>
                     {{Xtest1 | safe}}
                    <!-- figure {{ figure | safe}} -->
                    &nbsp;
                    <h5 style="color:rgb(25, 116, 236);font-family:verdana;"> <b>Ttest </b>  </h5>
                     {{Ttest1 | safe}}
                     &nbsp;
                    <h5 style="color:rgb(25, 116, 236);font-family:verdana;"> <b>Xtrain Graph </b>  </h5>
                       {{ figure | safe}}
                     <!-- model {{model | safe}} -->
                     &nbsp;
                     <form action="{% url 'MachineLearningApi:CreateModel' %}">
                            <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> CreateModel</button>
                            </form>
                            
                     
            </tr>
        <!-- {{test}}
        {% for ad in test %} -->
        
    <!-- {% endfor %} -->
    </tbody>
</table>
{% endblock %}

simplesocial/templates/datacleaned.html
{% extends "base.html" %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Badr Hashmi</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
  <!-- Alternative to Bootstrap 3 Glyphicons -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">
</head>

{% block content %}
<h1>Data Cleaning results </h1>
<form action="{% url 'MachineLearningApi:replaceValues' %}" method="POST" class="post-form">
  {% csrf_token %}
  <table>
    {% for item in users %}
    <tr>
        <td><b>changeTypeCol:</b>{{ item.DropcolName  }}<b> replacevaluesWith:</b>{{ item.replacevaluesWith }}<b></td>
        <td><b>valueToBeReplaced:</b> {{ item.valueToBeReplaced |default:"NA" }}</td>   
   </tr>
   <tr>
   <td colspan="2" class="divider"><hr/></td>
</tr>
   {% endfor %}
</table>
<form action="{% url 'MachineLearningApi:preprocess' %}"  >
   <button class="btn btn-primary active" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> Confirm</button>
   </form>
</form>
{% endblock %}

simplesocial/templates/datacleaned_displaychanges.html
{% extends "base.html" %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Badr Hashmi</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

  <!-- Alternative to Bootstrap 3 Glyphicons -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>
{% block content %}
<h1>  Data Cleaning Changed Data </h1>


<form action="{% url 'MachineLearningApi:datacleanedchanges' %}" method="POST" class="post-form">
  {% csrf_token %}
  <table>
    {% for item in users %}
    <tr>
        <td><b>changeTypeCol:</b>{{ item.changeTypeCol  }}<b> changeColTypeTo:</b>{{ item.changeColTypeTo }}<b></td>
        <!-- <td><b>Gender:</b> {{ item.inputcols |default:"NA" }}</td> -->
       
   </tr>
   <tr>
   <td colspan="2" class="divider"><hr/></td>
</tr>
   {% endfor %}
</table>
<!-- <button type="submit" class="save btn btn-default">Save</button>  -->
<form action="{% url 'MachineLearningApi:datacleanedchanges' %}"  >
   <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> Display Data Changes </button>
   </form>
</form>



<!-- <form action="{% url 'MachineLearningApi:preprocess' %}">
   <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> Preprocess</button>
   </form> -->
{% endblock %}

simplesocial/templates/datacleaning.html
{% extends "base.html" %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Badr Hashmi</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

  <!-- Alternative to Bootstrap 3 Glyphicons -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>
{% block content %}
<h1> Welcome to Data Cleaning</h1>

    <form action="{% url 'MachineLearningApi:datacleaned' %}" method="POST">
       {% csrf_token %}
       <table>
        {{df}}
        {{form.as_table}}

    
     </table>
        <tr>
        <td colspan="2" class="divider"><hr/></td>
    </tr>
        
    </table>
     <!-- <button type="submit" class="save btn btn-default">Save</button>  -->
     <input type="submit" value="Submit" />
    </form>

    

    <!-- <form action="{% url 'MachineLearningApi:preprocess' %}">
        <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> Preprocess</button>
        </form> -->
{% endblock %}

simplesocial/templates/details.html
{% extends 'create.html' %}
{% block replace %}
<CENTER>
<div class="jumbotron">
  <h1 class="display-4">Welcome to DataFlair<br>Hello {{ user_pr.fname }}</h1>
  <p class="lead">its an awesome profile picture</p>
  <hr class="my-4">
  <img src="{{ user_pr.display_picture.url }}" class="image_responsive" height="100px" width="100px">
  <p>
    {{ user_pr.display_picture.url }}<BR>
   You have learned some awesome technologies like {{ user_pr.technologies }}</p>
</div>
</CENTER>
{% endblock %}

simplesocial/templates/display.html
{% extends "base.html" %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Badr Hashmi</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

  <!-- Alternative to Bootstrap 3 Glyphicons -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

</head>
{% block content %}
<h1> Welcome to Machine Learning Api</h1>

    <form action="{% url 'MachineLearningApi:datacleaning' %}" method="POST" class="post-form">
       {% csrf_token %}
       <table>
        {% for item in users %}
        <tr>
            <td><b>changeColTypeTo:</b>{{ item.changeColTypeTo }}</td>
            <td><b>changeCol:</b> {{ item.changeTypeCol |default:"NA" }}</td>
            
        </tr>
        <tr>
        <td colspan="2" class="divider"><hr/></td>
    </tr>
        {% endfor %}
    </table>
     <!-- <button type="submit" class="save btn btn-default">Save</button>  -->
     <form action="{% url 'MachineLearningApi:datacleaning' %}"  >
        <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> Confirm</button>
        </form>
    </form>

    

    <!-- <form action="{% url 'MachineLearningApi:preprocess' %}">
        <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> Preprocess</button>
        </form> -->
{% endblock %}

simplesocial/templates/error.html
{% extends 'profile_maker/create.html' %}
{% block replace %}
<CENTER>
    <h1 style = 'border: 5px red solid;'> hello, you have uploaded the wrong file type.</h1>
</CENTER>
{% endblock %}

simplesocial/templates/preprocess.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<h2 style="color:rgb(87, 6, 30);font-family:verdana;"> <b>Let's Look at the Uploaded Data </b>  </h2>


<table class="table table-bordered" id="dataTable" width="100%" cellspacing="100">
    <thead>
        <!-- <tr>
                {{loaded_data | safe}}
        </tr> -->

    </thead>
    <!-- <form action="{% url 'MachineLearningApi:display' %}" method="post"> -->
    <!-- <form action="{% url 'MachineLearningApi:partitiondata' %}" method="post">    
        {% csrf_token %}
        <table>
        {{form.as_table}}
    
     </table>
    <input type="submit" value="Submit" /> -->

    <tbody>
            <tr> <p>This data was collected by Luis Candanedo, at  University of Mons (UMONS). It is experimental data used to create regression models of appliances energy use in a low energy building.The  original number of samples in the data are 19735 and number of attributes are 29.The target is whatever the output of the input variables.We will chose the second attribute as our target values(lights).Features are individual independent variables that act as the input in your system. Prediction models use features to make predictions. The  other attributes displayed below will form the input data.</p>
                    {{loaded_data | safe}}
                    &nbsp;
                    <p>I had previously mentioned that the lights data will be used as a target values for this exercise.</p>
                    &nbsp;
                    <h2 style="color:rgb(25, 28, 236);font-family:verdana;"> <b>Lights Data </b>  </h2>
                    &nbsp;
                    {{filedatahtml | safe}}
                    &nbsp;
                    <h2 style="color:rgb(25, 28, 236);font-family:verdana;"> <b>Lights Data Graph </b>  </h2>
                    &nbsp;
                     <!-- Xtrain {{Xtrain | safe}}
                     Ttrain {{Ttrain | safe}}
                     Xtest {{Xtest| safe}}
                     Ttest {{Ttest | safe}} -->
                     {{ figure | safe}} 
                     &nbsp;
                     

                    <form action="{% url 'MachineLearningApi:partitiondata' %}">
                        <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> partitiondata</button>
                        </form>
                     
                      {{Xtrain1 | safe}}
                      {{Ttrain1 | safe}}
                      {{Xtest1| safe}}
                      {{Ttest1 | safe}}
                     
            </tr>
            <br> </br>
            <form action="{% url 'MachineLearningApi:display' %}"  >
                <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> New Target values</button>
                </form>
        <!-- {{test}}
        {% for ad in test %} -->
        
    <!-- {% endfor %} -->

    <!-- <form action="{% url 'MachineLearningApi:display' %}">
        <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"> display</button>
        </form> -->
    </tbody>
</table>
{% endblock %}

simplesocial/templates/thanks.html
{% extends "base.html" %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Badr Hashmi</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Optional theme -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

  <!-- Alternative to Bootstrap 3 Glyphicons -->
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

  

</head>
{% block content %}

<h2 style="color:rgb(25, 28, 236);font-family:verdana;"> <b>Welcome to Machine Learning Exercise </b>  </h2>
<p> The purpose is to learn about linear regression in the machine learning. When we say Linear Regression algorithm, it means a set of functions that define similar characteristics as defined by Linear Regression and from those set of functions we will choose one function that fits the most by the training data.
  <br><br> We will use available sample data to develop  a simple linear model on different training data while minimizing the error produced by the model.A machine learning model is a mathematical representation of a real-world process.To generate a machine learning model you will need to provide training data to a machine learning algorithm to learn from. I will be developing a model by standardizing the training data and making predictions about the data. I will use a technique known as RMSE method to see how good the model is at making predictions. </p>
<body>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Important Note
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header" style="background-color:lightblue">
          <h5 class="modal-title" id="exampleModalLabel">Note</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" style="background-color:lightblue">
          If you would not like to load any data and rather use the default data, you can proceed to the next step by clicking  Show File Data
        </div>
        
        
      </div>
    </div>
  </div>
    
    </body>
<form action="{% url "MachineLearningApi:upload_csv" %}" method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">File: </label>
        <div class="col-md-8">
            <input type="file" name="csv_file" id="csv_file" required="True" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
             <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload" style="margin-right:5px;"></span>Upload </button>
        </div>
    </div>

    </form>

    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
    {% endfor %}

    <form action="{% url 'MachineLearningApi:preprocess' %}">
        <button class="btn btn-primary" type='submit'> <span class="glyphicon glyphicon-upload" style="margin-right:5px;">  Show File Data</button>
        </form>


       
        
{% endblock %}

simplesocial/templates/userdetails.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Forms Tutorial</title>
</head>
<body>
<h2>Data cleaning module </h2>

<form action="{% url 'MachineLearningApi:display' %}" method="post">
    {% csrf_token %}
    <table>
    {{form.as_table}}

 </table>
<input type="submit" value="Submit" />
</form>


</body>
{% endblock %}